# 資料爬取
網站:https://med.nhi.gov.tw/ihqe0000/IHQE0010S01.aspx?Type=DM

In [ ]:
import re
import requests
from bs4 import BeautifulSoup
import json

In [2]:
# 從網站收集資料
# headers設定
headers={
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
}

# 網站網址
url='https://med.nhi.gov.tw/ihqe0000/IHQE0020S03.ashx'

# Get 參數設定
# 取出參數鍵與值
sourse='type=DM&year=9512&HOSP_ID=&code=114&name=&category=&area=31'
list_payload=re.split('[&]',sourse)
payload={}
for i in list_payload:
    a=re.split('=',i)
    payload[a[0]]=a[1] 

# 設定索取資料所需內容值
year_list=[str(i)+'12' for i in range(95,113)]
for year in year_list:
    payload['year']=year
    response_eye=requests.get(url,headers=headers,params=payload)
    response_eye.encoding='utf-8'
    request_eye=json.loads(response_eye.text)

    # 排除空資料
    if len(request_eye)==0:
        x=1
    elif x==1:
        df_eye=pd.DataFrame(request_eye)
        df_eye['year']=int(year[0:-2])+1911
        x=2
    else:
        df=pd.DataFrame(request_eye)
        df['year']=int(year[0:-2])+1911
        df_eye=pd.concat([df_eye,df],axis=0)

In [6]:
# 查看df
display(df_eye.head())
df_eye.tail()

,amount,branch_type,category,da_id,hospital_area,hospital_code,hospital_name,indicator,total,Special_Type,SPECIAL_ID,overall_district,overall,year
0,4412,1,醫學中心,114,新北市板橋區,1131010011,醫療財團法人徐元智先生醫藥基金會亞東紀念醫院,24.57%,17954,1,0,0.2483,0.3040,2011
1,2775,1,區域醫院,114,新北市新店區,1131050515,佛教慈濟醫療財團法人台北慈濟醫院,25.22%,10999,2,0,0.2483,0.3040,2011
2,2941,1,區域醫院,114,新北市中和區,1331040513,衛生福利部雙和醫院〈委託臺北醫學大學興建經營〉,36.34%,8091,2,0,0.2483,0.3040,2011
3,2959,1,區域醫院,114,新北市新店區,1231050017,天主教耕莘醫療財團法人耕莘醫院,39.52%,7486,2,0,0.2483,0.3040,2011
4,1346,1,區域醫院,114,新北市三峽區,1131090019,行天宮醫療志業醫療財團法人恩主公醫院,18.66%,7212,2,0,0.2483,0.3040,2011

,amount,branch_type,category,da_id,hospital_area,hospital_code,hospital_name,indicator,total,Special_Type,SPECIAL_ID,overall_district,overall,year
1094,1.0000,1,診所,114,新北市林口區,3531171484,未來小兒科診所,100%,1.0000,4,0,0.4474,0.4793,2023
1095,1.0000,1,診所,114,新北市林口區,3531171546,未來婦產科診所,100%,1.0000,4,0,0.4474,0.4793,2023
1096,0.0000,1,診所,114,新北市金山區,3531270188,東大診所,0%,1.0000,4,0,0.4474,0.4793,2023
1097,0.0000,1,診所,114,新北市五股區,3531151839,倍康復健科診所,0%,1.0000,4,0,0.4474,0.4793,2023
1098,0.0000,1,診所,114,新北市板橋區,3531012677,雷世陽婦產科診所,0%,1.0000,4,0,0.4474,0.4793,2023

In [7]:
# 查看df資訊
df_eye.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11096 entries, 0 to 1098
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   amount            11096 non-null  object
 1   branch_type       11096 non-null  object
 2   category          11096 non-null  object
 3   da_id             11096 non-null  object
 4   hospital_area     11096 non-null  object
 5   hospital_code     11096 non-null  object
 6   hospital_name     11096 non-null  object
 7   indicator         11096 non-null  object
 8   total             11096 non-null  object
 9   Special_Type      11096 non-null  object
 10  SPECIAL_ID        11096 non-null  object
 11  overall_district  11096 non-null  object
 12  overall           11096 non-null  object
 13  year              11096 non-null  int64
dtypes: int64(1), object(13)
memory usage: 1.3+ MB

In [16]:
# 匯出原始資料
df_eye.to_csv('./data/DFE_row.csv',encoding='utf-8-sig')